# Project: malloc
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/tools/RedDevC++/MinGW32/lib/gcc/i686-w64-mingw32/10.3.0/" -L"C:/tools/RedDevC++/MinGW32/lib/gcc/" -L"C:/tools/RedDevC++/MinGW32/i686-w64-mingw32/lib/" -L"C:/tools/RedDevC++/MinGW32/lib/" -L"C:/tools/RedDevC++/MinGW32/lib" -L"C:/tools/RedDevC++/MinGW32/i686-w64-mingw32/lib" -g3 -static
INCS     = -I"C:/tools/RedDevC++/MinGW32/lib/gcc/i686-w64-mingw32/10.3.0/include" -I"C:/tools/RedDevC++/MinGW32/include" -I"C:/tools/RedDevC++/MinGW32/lib/gcc/i686-w64-mingw32/10.3.0/include-fixed" -I"C:/tools/RedDevC++/MinGW32/i686-w64-mingw32/include"
CXXINCS  = -I"C:/tools/RedDevC++/MinGW32/include/c++/10.3.0" -I"C:/tools/RedDevC++/MinGW32/include/c++/10.3.0/i686-w64-mingw32" -I"C:/tools/RedDevC++/MinGW32/include/c++/10.3.0/backward" -I"C:/tools/RedDevC++/MinGW32/lib/gcc/i686-w64-mingw32/10.3.0/include" -I"C:/tools/RedDevC++/MinGW32/include" -I"C:/tools/RedDevC++/MinGW32/lib/gcc/i686-w64-mingw32/10.3.0/include-fixed" -I"C:/tools/RedDevC++/MinGW32/i686-w64-mingw32/include"
BIN      = malloc.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -g3 -std=c11
ENCODINGS = -finput-charset=utf-8 -fexec-charset=ks_c_5601-1987
CFLAGS   = $(INCS) -Wall -Wextra -g3 -std=c11
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "$(BIN)" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS) 
